name: pkg

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: 2.x
    - name: install dependencies
      run: deno install
    - name: echo steps
      env:
        STEPS: ${{ toJSON(steps) }}
      run: echo "$STEPS"
    - name: package executable
      run: ./bin/compile
    - name: upload release files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v2
      with:
        files: pkg/*
