name: test

on:
  push:
    branches:
      - master
      - 'releases/*'
      - 'pull-req/*'
      - 'dependabot/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: install dependencies
        run: deno install
      - name: lint
        run: deno lint
      - name: test
        run: deno task test
