name: test

on:
  push:
    branches:
      - master
      - 'releases/*'
      - 'pull-req/*'
      - 'dependabot/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: install yarn
        run: npm install -g yarn
      - name: install npms /w yarn
        run: yarn install
      - name: lint
        run: yarn run lint
      - name: test
        run: yarn run test
